host_project_id        = ""
service_project_id     = ""
database_version       = "MYSQL_8_0"
cloudsql_instance_name = ""
region                 = ""
zone                   = ""
subnetwork_ip_cidr     = ""
## User Project Details
user_project_id            = ""
user_region                = ""
uservpc_subnetwork_ip_cidr = ""
